//! AUTO-EXTRACTED submodule of `dispatch`. Generated by the PR 7 split.
//!
//! Section: Advisory / Reporting Switches

#![allow(unused_imports, clippy::wildcard_imports)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::Ordering;

use hla_core::{
    AttributeHandle, AttributeHandleSet, AttributeHandleValueMap, FederateHandle,
    InteractionClassHandle, ObjectClassHandle, ObjectInstanceHandle, ParameterHandleValueMap,
};
use hla_fedpro_proto::fedpro::{
    self, AttributeHandleSet as ProtoAttributeHandleSet, CreateFederationExecutionResponse,
    DeleteObjectInstanceResponse, DestroyFederationExecutionResponse,
    DisableTimeConstrainedResponse, DisableTimeRegulationResponse, EnableTimeConstrainedResponse,
    EnableTimeRegulationResponse, ExceptionData, GetAttributeHandleResponse,
    GetAttributeNameResponse, GetInteractionClassHandleResponse, GetInteractionClassNameResponse,
    GetObjectClassHandleResponse, GetObjectClassNameResponse, GetParameterHandleResponse,
    GetParameterNameResponse, JoinFederationExecutionResponse,
    JoinFederationExecutionWithModulesResponse, JoinFederationExecutionWithNameAndModulesResponse,
    JoinFederationExecutionWithNameResponse, JoinResult, ListFederationExecutionsResponse,
    PublishInteractionClassResponse, PublishObjectClassAttributesResponse,
    QueryLogicalTimeResponse, QueryLookaheadResponse, RegisterObjectInstanceResponse,
    RegisterObjectInstanceWithNameResponse, ResignFederationExecutionResponse,
    SendInteractionResponse, SubscribeInteractionClassResponse,
    SubscribeObjectClassAttributesResponse, TimeAdvanceRequestResponse,
    UnpublishInteractionClassResponse, UnpublishObjectClassAttributesResponse,
    UnsubscribeInteractionClassResponse, UnsubscribeObjectClassAttributesResponse,
    UpdateAttributeValuesResponse, call_request::CallRequest as Req,
    call_response::CallResponse as Resp,
};

use crate::SyncPoint;
use crate::exception::HlaException;
use crate::handles::{
    HandleError, decode_attribute, decode_interaction_class, decode_object_class,
    decode_object_instance, decode_parameter, encode_attribute, encode_interaction_class,
    encode_object_class, encode_object_instance, encode_parameter,
};
use crate::routing::{
    OutboundCallback, announce_synchronization_point, attribute_is_not_owned,
    attribute_ownership_acquisition_notification, attribute_ownership_unavailable,
    decode_logical_time, decode_logical_time_interval, discover_object_instance,
    encode_logical_time, encode_logical_time_interval, fan_out, federation_not_restored,
    federation_not_saved, federation_restore_begun, federation_restored, federation_saved,
    federation_synchronized, inform_attribute_ownership, initiate_federate_restore,
    initiate_federate_save, live_connections, receive_directed_interaction, receive_interaction,
    receive_interaction_with_time, reflect_attribute_values, reflect_attribute_values_with_time,
    remove_object_instance, remove_object_instance_with_time, request_federation_restore_failed,
    request_federation_restore_succeeded, start_registration_for_object_class,
    stop_registration_for_object_class, subscribers_for_attributes, subscribers_for_interaction,
    synchronization_point_registration_failed, synchronization_point_registration_succeeded,
    time_advance_grant, time_constrained_enabled, time_regulation_enabled, turn_interactions_off,
    turn_interactions_on,
};
use crate::session::{Membership, SessionContext};
use crate::time::try_grant_pending_advances;
use crate::{FederateSession, Federation, ObjectInstance, PubSubState, RtiNode};
use crate::{RestoreOperation, RestoreStatus, SaveOperation, SaveStatus};

use super::*;

pub(super) fn get_switch_bool<G, W>(ctx: &SessionContext, getter: G, wrap: W) -> Resp
where
    G: Fn(&crate::Switches) -> bool,
    W: Fn(bool) -> Resp,
{
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let federates = m.federation.federates.read();
    match federates.get(&m.federate_handle) {
        Some(fs) => wrap(getter(&fs.switches)),
        None => exception_variant(HlaException::FederateNotExecutionMember, ""),
    }
}

pub(super) fn set_switch_bool<S, W>(
    ctx: &mut SessionContext,
    value: bool,
    setter: S,
    wrap: W,
) -> Resp
where
    S: Fn(&mut crate::Switches, bool),
    W: Fn() -> Resp,
{
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let mut federates = m.federation.federates.write();
    match federates.get_mut(&m.federate_handle) {
        Some(fs) => {
            setter(&mut fs.switches, value);
            wrap()
        }
        None => exception_variant(HlaException::FederateNotExecutionMember, ""),
    }
}

pub(super) fn get_automatic_resign_directive(ctx: &SessionContext) -> Resp {
    use hla_fedpro_proto::fedpro::GetAutomaticResignDirectiveResponse;
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let federates = m.federation.federates.read();
    let fs = match federates.get(&m.federate_handle) {
        Some(f) => f,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    Resp::GetAutomaticResignDirectiveResponse(GetAutomaticResignDirectiveResponse {
        result: encode_resign_action(fs.switches.automatic_resign_directive),
    })
}

pub(super) fn set_automatic_resign_directive(ctx: &mut SessionContext, value: i32) -> Resp {
    use hla_fedpro_proto::fedpro::SetAutomaticResignDirectiveResponse;
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let action = match value {
        0 => hla_core::ResignAction::UnconditionallyDivestAttributes,
        1 => hla_core::ResignAction::DeleteObjects,
        2 => hla_core::ResignAction::CancelPendingOwnershipAcquisitions,
        3 => hla_core::ResignAction::DeleteObjectsThenDivest,
        4 => hla_core::ResignAction::CancelThenDeleteThenDivest,
        5 => hla_core::ResignAction::NoAction,
        other => return exception_variant(HlaException::InvalidResignAction, &other.to_string()),
    };
    let mut federates = m.federation.federates.write();
    match federates.get_mut(&m.federate_handle) {
        Some(fs) => {
            fs.switches.automatic_resign_directive = action;
            Resp::SetAutomaticResignDirectiveResponse(SetAutomaticResignDirectiveResponse {})
        }
        None => exception_variant(HlaException::FederateNotExecutionMember, ""),
    }
}

pub(super) fn encode_resign_action(a: hla_core::ResignAction) -> i32 {
    match a {
        hla_core::ResignAction::UnconditionallyDivestAttributes => 0,
        hla_core::ResignAction::DeleteObjects => 1,
        hla_core::ResignAction::CancelPendingOwnershipAcquisitions => 2,
        hla_core::ResignAction::DeleteObjectsThenDivest => 3,
        hla_core::ResignAction::CancelThenDeleteThenDivest => 4,
        hla_core::ResignAction::NoAction => 5,
    }
}
