//! AUTO-EXTRACTED submodule of `dispatch`. Generated by the PR 7 split.
//!
//! Section: DDM region lifecycle

#![allow(unused_imports, clippy::wildcard_imports, dead_code)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::Ordering;

use hla_core::{
    AttributeHandle, AttributeHandleSet, AttributeHandleValueMap, FederateHandle,
    InteractionClassHandle, ObjectClassHandle, ObjectInstanceHandle, ParameterHandleValueMap,
};
use hla_fedpro_proto::fedpro::{
    self, AttributeHandleSet as ProtoAttributeHandleSet, CreateFederationExecutionResponse,
    DeleteObjectInstanceResponse, DestroyFederationExecutionResponse,
    DisableTimeConstrainedResponse, DisableTimeRegulationResponse, EnableTimeConstrainedResponse,
    EnableTimeRegulationResponse, ExceptionData, GetAttributeHandleResponse,
    GetAttributeNameResponse, GetInteractionClassHandleResponse, GetInteractionClassNameResponse,
    GetObjectClassHandleResponse, GetObjectClassNameResponse, GetParameterHandleResponse,
    GetParameterNameResponse, JoinFederationExecutionResponse,
    JoinFederationExecutionWithModulesResponse, JoinFederationExecutionWithNameAndModulesResponse,
    JoinFederationExecutionWithNameResponse, JoinResult, ListFederationExecutionsResponse,
    PublishInteractionClassResponse, PublishObjectClassAttributesResponse,
    QueryLogicalTimeResponse, QueryLookaheadResponse, RegisterObjectInstanceResponse,
    RegisterObjectInstanceWithNameResponse, ResignFederationExecutionResponse,
    SendInteractionResponse, SubscribeInteractionClassResponse,
    SubscribeObjectClassAttributesResponse, TimeAdvanceRequestResponse,
    UnpublishInteractionClassResponse, UnpublishObjectClassAttributesResponse,
    UnsubscribeInteractionClassResponse, UnsubscribeObjectClassAttributesResponse,
    UpdateAttributeValuesResponse, call_request::CallRequest as Req,
    call_response::CallResponse as Resp,
};

use crate::SyncPoint;
use crate::exception::HlaException;
use crate::handles::{
    HandleError, decode_attribute, decode_interaction_class, decode_object_class,
    decode_object_instance, decode_parameter, encode_attribute, encode_interaction_class,
    encode_object_class, encode_object_instance, encode_parameter,
};
use crate::routing::{
    OutboundCallback, announce_synchronization_point, attribute_is_not_owned,
    attribute_ownership_acquisition_notification, attribute_ownership_unavailable,
    decode_logical_time, decode_logical_time_interval, discover_object_instance,
    encode_logical_time, encode_logical_time_interval, fan_out, federation_not_restored,
    federation_not_saved, federation_restore_begun, federation_restored, federation_saved,
    federation_synchronized, inform_attribute_ownership, initiate_federate_restore,
    initiate_federate_save, live_connections, receive_directed_interaction, receive_interaction,
    receive_interaction_with_time, reflect_attribute_values, reflect_attribute_values_with_time,
    remove_object_instance, remove_object_instance_with_time, request_federation_restore_failed,
    request_federation_restore_succeeded, start_registration_for_object_class,
    stop_registration_for_object_class, subscribers_for_attributes, subscribers_for_interaction,
    synchronization_point_registration_failed, synchronization_point_registration_succeeded,
    time_advance_grant, time_constrained_enabled, time_regulation_enabled, turn_interactions_off,
    turn_interactions_on,
};
use crate::session::{Membership, SessionContext};
use crate::time::try_grant_pending_advances;
use crate::{FederateSession, Federation, ObjectInstance, PubSubState, RtiNode};
use crate::{RestoreOperation, RestoreStatus, SaveOperation, SaveStatus};

use super::*;

pub(super) fn create_region(
    node: &Arc<RtiNode>,
    ctx: &SessionContext,
    dimensions: Option<fedpro::DimensionHandleSet>,
) -> Resp {
    use hla_fedpro_proto::fedpro::CreateRegionResponse;
    let _ = node;
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let dims: HashMap<hla_core::DimensionHandle, (u32, u32)> = dimensions
        .map(|d| {
            d.dimension_handle
                .iter()
                .filter_map(|h| {
                    if h.data.len() == 4 {
                        let raw = u32::from_be_bytes(h.data[..].try_into().unwrap());
                        Some((hla_core::DimensionHandle::new(raw), (0u32, u32::MAX)))
                    } else {
                        None
                    }
                })
                .collect()
        })
        .unwrap_or_default();
    let raw_id = m.federation.next_region_id.fetch_add(1, Ordering::Relaxed);
    let handle = hla_core::RegionHandle::new(raw_id);
    m.federation.regions.write().insert(
        handle,
        crate::Region {
            handle,
            owner: m.federate_handle,
            committed: dims.clone(),
            staged: dims,
        },
    );
    Resp::CreateRegionResponse(CreateRegionResponse {
        result: Some(fedpro::RegionHandle {
            data: raw_id.to_be_bytes().to_vec(),
        }),
    })
}

pub(super) fn commit_region_modifications(
    ctx: &SessionContext,
    regions: Option<fedpro::RegionHandleSet>,
) -> Resp {
    use hla_fedpro_proto::fedpro::CommitRegionModificationsResponse;
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let region_handles: Vec<hla_core::RegionHandle> = regions
        .map(|s| {
            s.region_handle
                .iter()
                .filter_map(|h| {
                    if h.data.len() == 8 {
                        Some(hla_core::RegionHandle::new(u64::from_be_bytes(
                            h.data[..].try_into().unwrap(),
                        )))
                    } else {
                        None
                    }
                })
                .collect()
        })
        .unwrap_or_default();
    let mut regions = m.federation.regions.write();
    for rh in region_handles {
        if let Some(r) = regions.get_mut(&rh) {
            if r.owner != m.federate_handle {
                return exception_variant(HlaException::RegionNotCreatedByThisFederate, "");
            }
            r.committed = r.staged.clone();
        }
    }
    Resp::CommitRegionModificationsResponse(CommitRegionModificationsResponse {})
}

pub(super) fn delete_region(ctx: &SessionContext, region: Option<fedpro::RegionHandle>) -> Resp {
    use hla_fedpro_proto::fedpro::DeleteRegionResponse;
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let rh = match region {
        Some(h) if h.data.len() == 8 => {
            hla_core::RegionHandle::new(u64::from_be_bytes(h.data[..].try_into().unwrap()))
        }
        _ => return exception_variant(HlaException::InvalidRegion, ""),
    };
    let mut regions = m.federation.regions.write();
    match regions.get(&rh) {
        Some(r) if r.owner == m.federate_handle => {
            regions.remove(&rh);
            Resp::DeleteRegionResponse(DeleteRegionResponse {})
        }
        Some(_) => exception_variant(HlaException::RegionNotCreatedByThisFederate, ""),
        None => exception_variant(HlaException::InvalidRegion, ""),
    }
}

pub(super) fn get_range_bounds(
    ctx: &SessionContext,
    region: Option<fedpro::RegionHandle>,
    dimension: Option<fedpro::DimensionHandle>,
) -> Resp {
    use hla_fedpro_proto::fedpro::{GetRangeBoundsResponse, RangeBounds};
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let rh = match region {
        Some(h) if h.data.len() == 8 => {
            hla_core::RegionHandle::new(u64::from_be_bytes(h.data[..].try_into().unwrap()))
        }
        _ => return exception_variant(HlaException::InvalidRegion, ""),
    };
    let dh = match dimension {
        Some(h) if h.data.len() == 4 => {
            hla_core::DimensionHandle::new(u32::from_be_bytes(h.data[..].try_into().unwrap()))
        }
        _ => return exception_variant(HlaException::InvalidDimension, ""),
    };
    let regions = m.federation.regions.read();
    let r = match regions.get(&rh) {
        Some(r) => r,
        None => return exception_variant(HlaException::InvalidRegion, ""),
    };
    let bounds = r.committed.get(&dh).copied().unwrap_or((0, u32::MAX));
    Resp::GetRangeBoundsResponse(GetRangeBoundsResponse {
        result: Some(RangeBounds {
            lower: bounds.0,
            upper: bounds.1,
        }),
    })
}

pub(super) fn set_range_bounds(
    ctx: &SessionContext,
    region: Option<fedpro::RegionHandle>,
    dimension: Option<fedpro::DimensionHandle>,
    bounds: Option<fedpro::RangeBounds>,
) -> Resp {
    use hla_fedpro_proto::fedpro::SetRangeBoundsResponse;
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let rh = match region {
        Some(h) if h.data.len() == 8 => {
            hla_core::RegionHandle::new(u64::from_be_bytes(h.data[..].try_into().unwrap()))
        }
        _ => return exception_variant(HlaException::InvalidRegion, ""),
    };
    let dh = match dimension {
        Some(h) if h.data.len() == 4 => {
            hla_core::DimensionHandle::new(u32::from_be_bytes(h.data[..].try_into().unwrap()))
        }
        _ => return exception_variant(HlaException::InvalidDimension, ""),
    };
    let bounds = match bounds {
        Some(b) if b.lower <= b.upper => (b.lower, b.upper),
        Some(_) => return exception_variant(HlaException::InvalidRangeBound, "lower > upper"),
        None => return exception_variant(HlaException::InvalidRangeBound, "missing"),
    };
    let mut regions = m.federation.regions.write();
    match regions.get_mut(&rh) {
        Some(r) if r.owner == m.federate_handle => {
            r.staged.insert(dh, bounds);
            Resp::SetRangeBoundsResponse(SetRangeBoundsResponse {})
        }
        Some(_) => exception_variant(HlaException::RegionNotCreatedByThisFederate, ""),
        None => exception_variant(HlaException::InvalidRegion, ""),
    }
}
