//! AUTO-EXTRACTED submodule of `dispatch`. Generated by the PR 7 split.
//!
//! Section: DDM region-overlap matching

#![allow(unused_imports, clippy::wildcard_imports)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::Ordering;

use hla_core::{
    AttributeHandle, AttributeHandleSet, AttributeHandleValueMap, FederateHandle,
    InteractionClassHandle, ObjectClassHandle, ObjectInstanceHandle, ParameterHandleValueMap,
};
use hla_fedpro_proto::fedpro::{
    self, AttributeHandleSet as ProtoAttributeHandleSet, CreateFederationExecutionResponse,
    DeleteObjectInstanceResponse, DestroyFederationExecutionResponse,
    DisableTimeConstrainedResponse, DisableTimeRegulationResponse, EnableTimeConstrainedResponse,
    EnableTimeRegulationResponse, ExceptionData, GetAttributeHandleResponse,
    GetAttributeNameResponse, GetInteractionClassHandleResponse, GetInteractionClassNameResponse,
    GetObjectClassHandleResponse, GetObjectClassNameResponse, GetParameterHandleResponse,
    GetParameterNameResponse, JoinFederationExecutionResponse,
    JoinFederationExecutionWithModulesResponse, JoinFederationExecutionWithNameAndModulesResponse,
    JoinFederationExecutionWithNameResponse, JoinResult, ListFederationExecutionsResponse,
    PublishInteractionClassResponse, PublishObjectClassAttributesResponse,
    QueryLogicalTimeResponse, QueryLookaheadResponse, RegisterObjectInstanceResponse,
    RegisterObjectInstanceWithNameResponse, ResignFederationExecutionResponse,
    SendInteractionResponse, SubscribeInteractionClassResponse,
    SubscribeObjectClassAttributesResponse, TimeAdvanceRequestResponse,
    UnpublishInteractionClassResponse, UnpublishObjectClassAttributesResponse,
    UnsubscribeInteractionClassResponse, UnsubscribeObjectClassAttributesResponse,
    UpdateAttributeValuesResponse, call_request::CallRequest as Req,
    call_response::CallResponse as Resp,
};

use crate::SyncPoint;
use crate::exception::HlaException;
use crate::handles::{
    HandleError, decode_attribute, decode_interaction_class, decode_object_class,
    decode_object_instance, decode_parameter, encode_attribute, encode_interaction_class,
    encode_object_class, encode_object_instance, encode_parameter,
};
use crate::routing::{
    OutboundCallback, announce_synchronization_point, attribute_is_not_owned,
    attribute_ownership_acquisition_notification, attribute_ownership_unavailable,
    decode_logical_time, decode_logical_time_interval, discover_object_instance,
    encode_logical_time, encode_logical_time_interval, fan_out, federation_not_restored,
    federation_not_saved, federation_restore_begun, federation_restored, federation_saved,
    federation_synchronized, inform_attribute_ownership, initiate_federate_restore,
    initiate_federate_save, live_connections, receive_directed_interaction, receive_interaction,
    receive_interaction_with_time, reflect_attribute_values, reflect_attribute_values_with_time,
    remove_object_instance, remove_object_instance_with_time, request_federation_restore_failed,
    request_federation_restore_succeeded, start_registration_for_object_class,
    stop_registration_for_object_class, subscribers_for_attributes, subscribers_for_interaction,
    synchronization_point_registration_failed, synchronization_point_registration_succeeded,
    time_advance_grant, time_constrained_enabled, time_regulation_enabled, turn_interactions_off,
    turn_interactions_on,
};
use crate::session::{Membership, SessionContext};
use crate::time::try_grant_pending_advances;
use crate::{FederateSession, Federation, ObjectInstance, PubSubState, RtiNode};
use crate::{RestoreOperation, RestoreStatus, SaveOperation, SaveStatus};

use super::*;

/// Returns true if `pub_regions` and `sub_regions` have ANY pair of regions
/// that overlap. Empty `pub_regions` OR empty `sub_regions` is treated as
/// "unrestricted" and always matches (legacy non-DDM subscription/update).
pub(super) fn regions_overlap_any(
    federation: &Federation,
    pub_regions: &std::collections::HashSet<hla_core::RegionHandle>,
    sub_regions: &std::collections::HashSet<hla_core::RegionHandle>,
) -> bool {
    if pub_regions.is_empty() || sub_regions.is_empty() {
        return true;
    }
    let regions = federation.regions.read();
    for p in pub_regions {
        for s in sub_regions {
            let (Some(rp), Some(rs)) = (regions.get(p), regions.get(s)) else {
                continue;
            };
            // For each dimension shared by both, ranges must intersect.
            // Dimensions only in one are treated as full-range, which
            // always intersects.
            let shared: Vec<&hla_core::DimensionHandle> = rp
                .committed
                .keys()
                .filter(|d| rs.committed.contains_key(d))
                .collect();
            let all_intersect = shared.iter().all(|d| {
                let (lp, up) = rp.committed[d];
                let (ls, us) = rs.committed[d];
                lp <= us && ls <= up
            });
            if all_intersect {
                return true;
            }
        }
    }
    false
}

/// Filter `subscribers` down to those whose region-restricted subscription
/// to (class, attr) overlaps the instance's regions for that attribute.
/// Subscribers without region restrictions pass through unfiltered.
pub(super) fn filter_subscribers_by_regions(
    federation: &Federation,
    subscribers: std::collections::HashSet<FederateHandle>,
    instance: ObjectInstanceHandle,
    class: ObjectClassHandle,
    attr: AttributeHandle,
) -> std::collections::HashSet<FederateHandle> {
    let pub_regions = {
        let instances = federation.object_instances.read();
        match instances.get(&instance) {
            Some(i) => i.attribute_regions.get(&attr).cloned().unwrap_or_default(),
            None => return std::collections::HashSet::new(),
        }
    };
    if pub_regions.is_empty() {
        // Unrestricted publisher: everyone matches.
        return subscribers;
    }
    let federates = federation.federates.read();
    subscribers
        .into_iter()
        .filter(|fh| {
            let fs = match federates.get(fh) {
                Some(f) => f,
                None => return false,
            };
            let sub_regions = fs
                .pub_sub
                .subscribed_attrs_regions
                .get(&(class, attr))
                .cloned()
                .unwrap_or_default();
            regions_overlap_any(federation, &pub_regions, &sub_regions)
        })
        .collect()
}
