//! AUTO-EXTRACTED submodule of `dispatch`. Generated by the PR 7 split.
//!
//! Section: Federation Management

#![allow(unused_imports, clippy::wildcard_imports, dead_code)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::Ordering;

use hla_core::{
    AttributeHandle, AttributeHandleSet, AttributeHandleValueMap, FederateHandle,
    InteractionClassHandle, ObjectClassHandle, ObjectInstanceHandle, ParameterHandleValueMap,
};
use hla_fedpro_proto::fedpro::{
    self, AttributeHandleSet as ProtoAttributeHandleSet, CreateFederationExecutionResponse,
    DeleteObjectInstanceResponse, DestroyFederationExecutionResponse,
    DisableTimeConstrainedResponse, DisableTimeRegulationResponse, EnableTimeConstrainedResponse,
    EnableTimeRegulationResponse, ExceptionData, GetAttributeHandleResponse,
    GetAttributeNameResponse, GetInteractionClassHandleResponse, GetInteractionClassNameResponse,
    GetObjectClassHandleResponse, GetObjectClassNameResponse, GetParameterHandleResponse,
    GetParameterNameResponse, JoinFederationExecutionResponse,
    JoinFederationExecutionWithModulesResponse, JoinFederationExecutionWithNameAndModulesResponse,
    JoinFederationExecutionWithNameResponse, JoinResult, ListFederationExecutionsResponse,
    PublishInteractionClassResponse, PublishObjectClassAttributesResponse,
    QueryLogicalTimeResponse, QueryLookaheadResponse, RegisterObjectInstanceResponse,
    RegisterObjectInstanceWithNameResponse, ResignFederationExecutionResponse,
    SendInteractionResponse, SubscribeInteractionClassResponse,
    SubscribeObjectClassAttributesResponse, TimeAdvanceRequestResponse,
    UnpublishInteractionClassResponse, UnpublishObjectClassAttributesResponse,
    UnsubscribeInteractionClassResponse, UnsubscribeObjectClassAttributesResponse,
    UpdateAttributeValuesResponse, call_request::CallRequest as Req,
    call_response::CallResponse as Resp,
};

use crate::SyncPoint;
use crate::exception::HlaException;
use crate::handles::{
    HandleError, decode_attribute, decode_interaction_class, decode_object_class,
    decode_object_instance, decode_parameter, encode_attribute, encode_interaction_class,
    encode_object_class, encode_object_instance, encode_parameter,
};
use crate::routing::{
    OutboundCallback, announce_synchronization_point, attribute_is_not_owned,
    attribute_ownership_acquisition_notification, attribute_ownership_unavailable,
    decode_logical_time, decode_logical_time_interval, discover_object_instance,
    encode_logical_time, encode_logical_time_interval, fan_out, federation_not_restored,
    federation_not_saved, federation_restore_begun, federation_restored, federation_saved,
    federation_synchronized, inform_attribute_ownership, initiate_federate_restore,
    initiate_federate_save, live_connections, receive_directed_interaction, receive_interaction,
    receive_interaction_with_time, reflect_attribute_values, reflect_attribute_values_with_time,
    remove_object_instance, remove_object_instance_with_time, request_federation_restore_failed,
    request_federation_restore_succeeded, start_registration_for_object_class,
    stop_registration_for_object_class, subscribers_for_attributes, subscribers_for_interaction,
    synchronization_point_registration_failed, synchronization_point_registration_succeeded,
    time_advance_grant, time_constrained_enabled, time_regulation_enabled, turn_interactions_off,
    turn_interactions_on,
};
use crate::session::{Membership, SessionContext};
use crate::time::try_grant_pending_advances;
use crate::{FederateSession, Federation, ObjectInstance, PubSubState, RtiNode};
use crate::{RestoreOperation, RestoreStatus, SaveOperation, SaveStatus};

use super::*;

pub(super) fn create_federation_inner(
    node: &Arc<RtiNode>,
    federation_name: String,
    proto_modules: Vec<fedpro::FomModule>,
) -> Result<(), Resp> {
    if federation_name.is_empty() {
        return Err(exception_variant(
            HlaException::ErrorReadingFdd,
            "federationName must not be empty",
        ));
    }
    let mut federations = node.federations.write();
    if federations.contains_key(&federation_name) {
        return Err(exception_variant(
            HlaException::FederationExecutionAlreadyExists,
            &federation_name,
        ));
    }
    let mut modules = Vec::new();
    for pm in &proto_modules {
        match decode_fom_module(pm) {
            Ok(m) => modules.push(m),
            Err(e) => return Err(exception_variant(HlaException::CouldNotOpenFdd, &e)),
        }
    }
    let fom = if modules.is_empty() {
        Arc::clone(&*node.default_fom.read())
    } else {
        match hla_omt::MergedFom::merge(modules) {
            Ok(m) => Arc::new(m),
            Err(e) => {
                return Err(exception_variant(
                    HlaException::ErrorReadingFdd,
                    &e.to_string(),
                ));
            }
        }
    };
    let federation = Arc::new(Federation::new(federation_name.clone(), fom));
    federations.insert(federation_name, federation);
    Ok(())
}

/// Extract the XML text from a `FomModule` oneof and parse it.
/// MVP supports `FileFomModule` (inline name + content) only. `compressedModule`
/// and `url` return `Err("unsupported FOM module form")`.
pub(super) fn decode_fom_module(pm: &fedpro::FomModule) -> Result<hla_omt::FomModule, String> {
    use fedpro::fom_module::FomModule as Variant;
    match pm.fom_module.as_ref() {
        Some(Variant::File(f)) => {
            let text = std::str::from_utf8(&f.content)
                .map_err(|e| format!("FOM module {:?} content is not UTF-8: {}", f.name, e))?;
            hla_omt::FomModule::parse(text).map_err(|e| format!("{}: {}", f.name, e))
        }
        Some(Variant::CompressedModule(_)) => {
            Err("compressed FOM modules not yet supported".into())
        }
        Some(Variant::Url(_)) => Err("URL FOM modules not yet supported".into()),
        None => Err("FomModule has no oneof variant set".into()),
    }
}

pub(super) fn destroy_federation_execution(node: &Arc<RtiNode>, federation_name: String) -> Resp {
    let mut federations = node.federations.write();
    let entry = match federations.get(&federation_name) {
        Some(e) => e,
        None => {
            return exception_variant(
                HlaException::FederationExecutionDoesNotExist,
                &federation_name,
            );
        }
    };
    if !entry.federates.read().is_empty() {
        return exception_variant(HlaException::FederatesCurrentlyJoined, &federation_name);
    }
    federations.remove(&federation_name);
    Resp::DestroyFederationExecutionResponse(DestroyFederationExecutionResponse {})
}

pub(super) fn join(
    node: &Arc<RtiNode>,
    ctx: &mut SessionContext,
    requested_name: Option<String>,
    federation_name: String,
) -> Result<JoinResult, Resp> {
    if ctx.is_joined() {
        return Err(exception_variant(
            HlaException::FederateAlreadyExecutionMember,
            &format!("session {}", ctx.session_id),
        ));
    }
    let federation = {
        let federations = node.federations.read();
        match federations.get(&federation_name) {
            Some(f) => Arc::clone(f),
            None => {
                return Err(exception_variant(
                    HlaException::FederationExecutionDoesNotExist,
                    &federation_name,
                ));
            }
        }
    };

    let raw_handle = federation.next_federate_id.fetch_add(1, Ordering::Relaxed);
    let federate_handle = FederateHandle::new(raw_handle);
    let federate_name = match requested_name {
        Some(n) => {
            let federates = federation.federates.read();
            if federates.values().any(|f| f.name == n) {
                return Err(exception_variant(
                    HlaException::FederateNameAlreadyInUse,
                    &n,
                ));
            }
            n
        }
        None => format!("federate-{raw_handle:08X}"),
    };

    federation.federates.write().insert(
        federate_handle,
        FederateSession {
            handle: federate_handle,
            name: federate_name.clone(),
            federate_type: String::new(),
            session_id: ctx.session_id,
            pub_sub: PubSubState::default(),
            time: crate::TimeState::default(),
            switches: crate::Switches::default(),
            tso_queue: Vec::new(),
        },
    );

    ctx.membership = Some(Membership {
        federation,
        federate_handle,
        federate_name,
    });

    Ok(JoinResult {
        federate_handle: Some(crate::handles::encode_federate(federate_handle)),
        logical_time_implementation_name: "HLAfloat64Time".to_string(),
    })
}

pub(super) fn resign(ctx: &mut SessionContext) -> Resp {
    let membership = match ctx.membership.take() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    membership
        .federation
        .federates
        .write()
        .remove(&membership.federate_handle);
    Resp::ResignFederationExecutionResponse(ResignFederationExecutionResponse {})
}
