//! AUTO-EXTRACTED submodule of `dispatch`. Generated by the PR 7 split.
//!
//! Section: Federate self-introspection

#![allow(unused_imports, clippy::wildcard_imports)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::Ordering;

use hla_core::{
    AttributeHandle, AttributeHandleSet, AttributeHandleValueMap, FederateHandle,
    InteractionClassHandle, ObjectClassHandle, ObjectInstanceHandle, ParameterHandleValueMap,
};
use hla_fedpro_proto::fedpro::{
    self, AttributeHandleSet as ProtoAttributeHandleSet, CreateFederationExecutionResponse,
    DeleteObjectInstanceResponse, DestroyFederationExecutionResponse,
    DisableTimeConstrainedResponse, DisableTimeRegulationResponse, EnableTimeConstrainedResponse,
    EnableTimeRegulationResponse, ExceptionData, GetAttributeHandleResponse,
    GetAttributeNameResponse, GetInteractionClassHandleResponse, GetInteractionClassNameResponse,
    GetObjectClassHandleResponse, GetObjectClassNameResponse, GetParameterHandleResponse,
    GetParameterNameResponse, JoinFederationExecutionResponse,
    JoinFederationExecutionWithModulesResponse, JoinFederationExecutionWithNameAndModulesResponse,
    JoinFederationExecutionWithNameResponse, JoinResult, ListFederationExecutionsResponse,
    PublishInteractionClassResponse, PublishObjectClassAttributesResponse,
    QueryLogicalTimeResponse, QueryLookaheadResponse, RegisterObjectInstanceResponse,
    RegisterObjectInstanceWithNameResponse, ResignFederationExecutionResponse,
    SendInteractionResponse, SubscribeInteractionClassResponse,
    SubscribeObjectClassAttributesResponse, TimeAdvanceRequestResponse,
    UnpublishInteractionClassResponse, UnpublishObjectClassAttributesResponse,
    UnsubscribeInteractionClassResponse, UnsubscribeObjectClassAttributesResponse,
    UpdateAttributeValuesResponse, call_request::CallRequest as Req,
    call_response::CallResponse as Resp,
};

use crate::SyncPoint;
use crate::exception::HlaException;
use crate::handles::{
    HandleError, decode_attribute, decode_interaction_class, decode_object_class,
    decode_object_instance, decode_parameter, encode_attribute, encode_interaction_class,
    encode_object_class, encode_object_instance, encode_parameter,
};
use crate::routing::{
    OutboundCallback, announce_synchronization_point, attribute_is_not_owned,
    attribute_ownership_acquisition_notification, attribute_ownership_unavailable,
    decode_logical_time, decode_logical_time_interval, discover_object_instance,
    encode_logical_time, encode_logical_time_interval, fan_out, federation_not_restored,
    federation_not_saved, federation_restore_begun, federation_restored, federation_saved,
    federation_synchronized, inform_attribute_ownership, initiate_federate_restore,
    initiate_federate_save, live_connections, receive_directed_interaction, receive_interaction,
    receive_interaction_with_time, reflect_attribute_values, reflect_attribute_values_with_time,
    remove_object_instance, remove_object_instance_with_time, request_federation_restore_failed,
    request_federation_restore_succeeded, start_registration_for_object_class,
    stop_registration_for_object_class, subscribers_for_attributes, subscribers_for_interaction,
    synchronization_point_registration_failed, synchronization_point_registration_succeeded,
    time_advance_grant, time_constrained_enabled, time_regulation_enabled, turn_interactions_off,
    turn_interactions_on,
};
use crate::session::{Membership, SessionContext};
use crate::time::try_grant_pending_advances;
use crate::{FederateSession, Federation, ObjectInstance, PubSubState, RtiNode};
use crate::{RestoreOperation, RestoreStatus, SaveOperation, SaveStatus};

use super::*;

pub(super) fn get_federate_handle(ctx: &SessionContext, name: &str) -> Resp {
    use crate::handles::encode_federate;
    use hla_fedpro_proto::fedpro::GetFederateHandleResponse;
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let federates = m.federation.federates.read();
    match federates.values().find(|f| f.name == name) {
        Some(fs) => Resp::GetFederateHandleResponse(GetFederateHandleResponse {
            result: Some(encode_federate(fs.handle)),
        }),
        None => exception_variant(HlaException::NameNotFound, name),
    }
}

pub(super) fn get_federate_name(ctx: &SessionContext, handle: fedpro::FederateHandle) -> Resp {
    use hla_fedpro_proto::fedpro::GetFederateNameResponse;
    let m = match ctx.membership.as_ref() {
        Some(m) => m,
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    let fh = match handle.data.len() {
        4 => FederateHandle::new(u32::from_be_bytes(handle.data[..].try_into().unwrap())),
        _ => return exception_variant(HlaException::InvalidFederateHandle, ""),
    };
    let federates = m.federation.federates.read();
    match federates.get(&fh) {
        Some(fs) => Resp::GetFederateNameResponse(GetFederateNameResponse {
            result: fs.name.clone(),
        }),
        None => exception_variant(HlaException::InvalidFederateHandle, ""),
    }
}

/// Well-known order types per IEEE 1516.1: Receive (0), TimeStamp (1).
pub(super) fn get_order_type(name: &str) -> Resp {
    use hla_fedpro_proto::fedpro::GetOrderTypeResponse;
    let raw = match name {
        "Receive" => 0i32,
        "TimeStamp" | "TimestampOrder" => 1i32,
        _ => return exception_variant(HlaException::InvalidOrderName, name),
    };
    Resp::GetOrderTypeResponse(GetOrderTypeResponse { result: raw })
}

pub(super) fn get_order_name(order_type: i32) -> Resp {
    use hla_fedpro_proto::fedpro::GetOrderNameResponse;
    let name = match order_type {
        0 => "Receive",
        1 => "TimeStamp",
        _ => return exception_variant(HlaException::InvalidOrderType, &order_type.to_string()),
    };
    Resp::GetOrderNameResponse(GetOrderNameResponse {
        result: name.to_string(),
    })
}

/// Well-known transportation types per IEEE 1516.1: HLAreliable (1), HLAbestEffort (2).
pub(super) fn get_transportation_type_handle(name: &str) -> Resp {
    use hla_fedpro_proto::fedpro::{GetTransportationTypeHandleResponse, TransportationTypeHandle};
    let raw: u32 = match name {
        "HLAreliable" => 1,
        "HLAbestEffort" => 2,
        _ => return exception_variant(HlaException::InvalidTransportationName, name),
    };
    Resp::GetTransportationTypeHandleResponse(GetTransportationTypeHandleResponse {
        result: Some(TransportationTypeHandle {
            data: raw.to_be_bytes().to_vec(),
        }),
    })
}

pub(super) fn get_transportation_type_name(handle: fedpro::TransportationTypeHandle) -> Resp {
    use hla_fedpro_proto::fedpro::GetTransportationTypeNameResponse;
    if handle.data.len() != 4 {
        return exception_variant(HlaException::InvalidTransportationTypeHandle, "");
    }
    let raw = u32::from_be_bytes(handle.data[..].try_into().unwrap());
    let name = match raw {
        1 => "HLAreliable",
        2 => "HLAbestEffort",
        _ => {
            return exception_variant(
                HlaException::InvalidTransportationTypeHandle,
                &raw.to_string(),
            );
        }
    };
    Resp::GetTransportationTypeNameResponse(GetTransportationTypeNameResponse {
        result: name.to_string(),
    })
}
