//! AUTO-EXTRACTED submodule of `dispatch`. Generated by the PR 7 split.
//!
//! Section: Object Management

#![allow(unused_imports, clippy::wildcard_imports, dead_code)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::Ordering;

use hla_core::{
    AttributeHandle, AttributeHandleSet, AttributeHandleValueMap, FederateHandle,
    InteractionClassHandle, ObjectClassHandle, ObjectInstanceHandle, ParameterHandleValueMap,
};
use hla_fedpro_proto::fedpro::{
    self, AttributeHandleSet as ProtoAttributeHandleSet, CreateFederationExecutionResponse,
    DeleteObjectInstanceResponse, DestroyFederationExecutionResponse,
    DisableTimeConstrainedResponse, DisableTimeRegulationResponse, EnableTimeConstrainedResponse,
    EnableTimeRegulationResponse, ExceptionData, GetAttributeHandleResponse,
    GetAttributeNameResponse, GetInteractionClassHandleResponse, GetInteractionClassNameResponse,
    GetObjectClassHandleResponse, GetObjectClassNameResponse, GetParameterHandleResponse,
    GetParameterNameResponse, JoinFederationExecutionResponse,
    JoinFederationExecutionWithModulesResponse, JoinFederationExecutionWithNameAndModulesResponse,
    JoinFederationExecutionWithNameResponse, JoinResult, ListFederationExecutionsResponse,
    PublishInteractionClassResponse, PublishObjectClassAttributesResponse,
    QueryLogicalTimeResponse, QueryLookaheadResponse, RegisterObjectInstanceResponse,
    RegisterObjectInstanceWithNameResponse, ResignFederationExecutionResponse,
    SendInteractionResponse, SubscribeInteractionClassResponse,
    SubscribeObjectClassAttributesResponse, TimeAdvanceRequestResponse,
    UnpublishInteractionClassResponse, UnpublishObjectClassAttributesResponse,
    UnsubscribeInteractionClassResponse, UnsubscribeObjectClassAttributesResponse,
    UpdateAttributeValuesResponse, call_request::CallRequest as Req,
    call_response::CallResponse as Resp,
};

use crate::SyncPoint;
use crate::exception::HlaException;
use crate::handles::{
    HandleError, decode_attribute, decode_interaction_class, decode_object_class,
    decode_object_instance, decode_parameter, encode_attribute, encode_interaction_class,
    encode_object_class, encode_object_instance, encode_parameter,
};
use crate::routing::{
    OutboundCallback, announce_synchronization_point, attribute_is_not_owned,
    attribute_ownership_acquisition_notification, attribute_ownership_unavailable,
    decode_logical_time, decode_logical_time_interval, discover_object_instance,
    encode_logical_time, encode_logical_time_interval, fan_out, federation_not_restored,
    federation_not_saved, federation_restore_begun, federation_restored, federation_saved,
    federation_synchronized, inform_attribute_ownership, initiate_federate_restore,
    initiate_federate_save, live_connections, receive_directed_interaction, receive_interaction,
    receive_interaction_with_time, reflect_attribute_values, reflect_attribute_values_with_time,
    remove_object_instance, remove_object_instance_with_time, request_federation_restore_failed,
    request_federation_restore_succeeded, start_registration_for_object_class,
    stop_registration_for_object_class, subscribers_for_attributes, subscribers_for_interaction,
    synchronization_point_registration_failed, synchronization_point_registration_succeeded,
    time_advance_grant, time_constrained_enabled, time_regulation_enabled, turn_interactions_off,
    turn_interactions_on,
};
use crate::session::{Membership, SessionContext};
use crate::time::try_grant_pending_advances;
use crate::{FederateSession, Federation, ObjectInstance, PubSubState, RtiNode};
use crate::{RestoreOperation, RestoreStatus, SaveOperation, SaveStatus};

use super::*;

pub(super) fn register_object_instance(
    node: &Arc<RtiNode>,
    ctx: &mut SessionContext,
    callbacks: &mut Vec<OutboundCallback>,
    class: Option<fedpro::ObjectClassHandle>,
    requested_name: Option<String>,
) -> Result<ObjectInstanceHandle, Resp> {
    let m = ctx
        .membership
        .as_ref()
        .ok_or_else(|| exception_variant(HlaException::FederateNotExecutionMember, ""))?
        .clone();
    let class = class
        .and_then(|h| decode_object_class(&h).ok())
        .ok_or_else(|| exception_variant(HlaException::InvalidObjectClassHandle, ""))?;
    if m.federation.fom.object_class_def(class).is_none() {
        return Err(exception_variant(HlaException::ObjectClassNotDefined, ""));
    }
    {
        let federates = m.federation.federates.read();
        let fs = federates
            .get(&m.federate_handle)
            .ok_or_else(|| exception_variant(HlaException::FederateNotExecutionMember, ""))?;
        if !fs.pub_sub.published_attrs.contains_key(&class) {
            return Err(exception_variant(HlaException::ObjectClassNotPublished, ""));
        }
    }

    let raw_id = m.federation.next_object_id.fetch_add(1, Ordering::Relaxed);
    let handle = ObjectInstanceHandle::new(raw_id);

    let name = match requested_name {
        Some(n) => {
            let instances = m.federation.object_instances.read();
            if instances.values().any(|inst| inst.name == n) {
                return Err(exception_variant(HlaException::ObjectInstanceNameInUse, &n));
            }
            n
        }
        None => format!("HLA{raw_id}"),
    };

    // Seed attribute ownership from the registrar's currently-published
    // attribute set for this class. (More precisely, from any ancestor of
    // this class that has a published attribute — but simpler: we use the
    // direct class's published set.) Per IEEE 1516.1 §7, attributes not
    // published by the registrar are not owned by anyone at registration
    // time.
    let attribute_owners: HashMap<AttributeHandle, FederateHandle> = {
        let federates = m.federation.federates.read();
        let fs = federates
            .get(&m.federate_handle)
            .ok_or_else(|| exception_variant(HlaException::FederateNotExecutionMember, ""))?;
        fs.pub_sub
            .published_attrs
            .get(&class)
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .map(|attr| (attr, m.federate_handle))
            .collect()
    };

    m.federation.object_instances.write().insert(
        handle,
        ObjectInstance {
            handle,
            class,
            name: name.clone(),
            registrar: m.federate_handle,
            attribute_owners,
            attribute_regions: HashMap::new(),
        },
    );

    // Fan-out `discoverObjectInstance` to every federate subscribed to this
    // class (or any ancestor). Subscribers are determined by the union of
    // subscriptions across attributes — any subscriber to the class hierarchy
    // should learn about the instance.
    notify_subscribers_of_registration(
        node,
        &m.federation,
        callbacks,
        handle,
        class,
        &name,
        m.federate_handle,
    );

    Ok(handle)
}

/// Identify every federate that has subscribed to *any* attribute of `class`
/// or any ancestor class, mark `instance` as discovered in their PubSubState,
/// and enqueue a `DiscoverObjectInstance` callback to each.
pub(super) fn notify_subscribers_of_registration(
    node: &Arc<RtiNode>,
    federation: &Federation,
    callbacks: &mut Vec<OutboundCallback>,
    instance: ObjectInstanceHandle,
    class: ObjectClassHandle,
    name: &str,
    producer: FederateHandle,
) {
    // O(subscribers) per ancestor via the `class_subscribers` reverse index,
    // not O(total subscription entries) which the old walk paid.
    let candidates = {
        let subs = federation.subscriptions.read();
        let mut out = std::collections::HashSet::new();
        for ancestor in federation.fom.inheritance_chain(class) {
            for fh in subs.subscribers_of_class(ancestor) {
                if fh != producer {
                    out.insert(fh);
                }
            }
        }
        out
    };

    let mut to_notify = Vec::new();
    {
        let mut federates = federation.federates.write();
        for fh in &candidates {
            if let Some(fs) = federates.get_mut(fh)
                && fs.pub_sub.discovered_instances.insert(instance)
            {
                to_notify.push(*fh);
            }
        }
    }
    let targets: std::collections::HashSet<FederateHandle> = to_notify.into_iter().collect();
    if targets.is_empty() {
        return;
    }

    let connections = live_connections(node, federation, &targets);
    fan_out(
        callbacks,
        &connections,
        discover_object_instance(instance, class, name, producer),
    );
}
