//! AUTO-EXTRACTED submodule of `dispatch`. Generated by the PR 7 split.
//!
//! Section: Synchronization Points

#![allow(unused_imports, clippy::wildcard_imports)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::Ordering;

use hla_core::{
    AttributeHandle, AttributeHandleSet, AttributeHandleValueMap, FederateHandle,
    InteractionClassHandle, ObjectClassHandle, ObjectInstanceHandle, ParameterHandleValueMap,
};
use hla_fedpro_proto::fedpro::{
    self, AttributeHandleSet as ProtoAttributeHandleSet, CreateFederationExecutionResponse,
    DeleteObjectInstanceResponse, DestroyFederationExecutionResponse,
    DisableTimeConstrainedResponse, DisableTimeRegulationResponse, EnableTimeConstrainedResponse,
    EnableTimeRegulationResponse, ExceptionData, GetAttributeHandleResponse,
    GetAttributeNameResponse, GetInteractionClassHandleResponse, GetInteractionClassNameResponse,
    GetObjectClassHandleResponse, GetObjectClassNameResponse, GetParameterHandleResponse,
    GetParameterNameResponse, JoinFederationExecutionResponse,
    JoinFederationExecutionWithModulesResponse, JoinFederationExecutionWithNameAndModulesResponse,
    JoinFederationExecutionWithNameResponse, JoinResult, ListFederationExecutionsResponse,
    PublishInteractionClassResponse, PublishObjectClassAttributesResponse,
    QueryLogicalTimeResponse, QueryLookaheadResponse, RegisterObjectInstanceResponse,
    RegisterObjectInstanceWithNameResponse, ResignFederationExecutionResponse,
    SendInteractionResponse, SubscribeInteractionClassResponse,
    SubscribeObjectClassAttributesResponse, TimeAdvanceRequestResponse,
    UnpublishInteractionClassResponse, UnpublishObjectClassAttributesResponse,
    UnsubscribeInteractionClassResponse, UnsubscribeObjectClassAttributesResponse,
    UpdateAttributeValuesResponse, call_request::CallRequest as Req,
    call_response::CallResponse as Resp,
};

use crate::SyncPoint;
use crate::exception::HlaException;
use crate::handles::{
    HandleError, decode_attribute, decode_interaction_class, decode_object_class,
    decode_object_instance, decode_parameter, encode_attribute, encode_interaction_class,
    encode_object_class, encode_object_instance, encode_parameter,
};
use crate::routing::{
    OutboundCallback, announce_synchronization_point, attribute_is_not_owned,
    attribute_ownership_acquisition_notification, attribute_ownership_unavailable,
    decode_logical_time, decode_logical_time_interval, discover_object_instance,
    encode_logical_time, encode_logical_time_interval, fan_out, federation_not_restored,
    federation_not_saved, federation_restore_begun, federation_restored, federation_saved,
    federation_synchronized, inform_attribute_ownership, initiate_federate_restore,
    initiate_federate_save, live_connections, receive_directed_interaction, receive_interaction,
    receive_interaction_with_time, reflect_attribute_values, reflect_attribute_values_with_time,
    remove_object_instance, remove_object_instance_with_time, request_federation_restore_failed,
    request_federation_restore_succeeded, start_registration_for_object_class,
    stop_registration_for_object_class, subscribers_for_attributes, subscribers_for_interaction,
    synchronization_point_registration_failed, synchronization_point_registration_succeeded,
    time_advance_grant, time_constrained_enabled, time_regulation_enabled, turn_interactions_off,
    turn_interactions_on,
};
use crate::session::{Membership, SessionContext};
use crate::time::try_grant_pending_advances;
use crate::{FederateSession, Federation, ObjectInstance, PubSubState, RtiNode};
use crate::{RestoreOperation, RestoreStatus, SaveOperation, SaveStatus};

use super::*;

pub(super) fn register_synchronization_point(
    node: &Arc<RtiNode>,
    ctx: &mut SessionContext,
    callbacks: &mut Vec<OutboundCallback>,
    label: String,
    tag: Vec<u8>,
    participant_subset: Option<std::collections::HashSet<FederateHandle>>,
) -> Resp {
    use hla_fedpro_proto::fedpro::RegisterFederationSynchronizationPointResponse;

    let m = match ctx.membership.as_ref() {
        Some(m) => m.clone(),
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };
    if label.is_empty() {
        return exception_variant(
            HlaException::InvalidSynchronizationPointLabel,
            "label must not be empty",
        );
    }

    // Determine participants: explicit subset or all currently-joined federates.
    let participants: std::collections::HashSet<FederateHandle> = match participant_subset {
        Some(s) if !s.is_empty() => s,
        _ => m.federation.federates.read().keys().copied().collect(),
    };

    // Reserve the slot under write lock so concurrent registers fail.
    let inserted = {
        let mut sync_points = m.federation.sync_points.write();
        if sync_points.contains_key(&label) {
            false
        } else {
            sync_points.insert(
                label.clone(),
                SyncPoint {
                    label: label.clone(),
                    tag: tag.clone(),
                    participants: participants.clone(),
                    achieved: std::collections::HashSet::new(),
                    failed_to_sync: std::collections::HashSet::new(),
                },
            );
            true
        }
    };

    if !inserted {
        // Failed-registration callback → only to the registrant.
        let registrant = live_connections(node, &m.federation, &single(m.federate_handle));
        fan_out(
            callbacks,
            &registrant,
            synchronization_point_registration_failed(&label, 0), // 0 = LABEL_NOT_UNIQUE
        );
    } else {
        // Succeeded callback → to the registrant.
        let registrant = live_connections(node, &m.federation, &single(m.federate_handle));
        fan_out(
            callbacks,
            &registrant,
            synchronization_point_registration_succeeded(&label),
        );
        // Announce callback → to every participant.
        let participants_conns = live_connections(node, &m.federation, &participants);
        fan_out(
            callbacks,
            &participants_conns,
            announce_synchronization_point(&label, &tag),
        );
    }

    Resp::RegisterFederationSynchronizationPointResponse(
        RegisterFederationSynchronizationPointResponse {},
    )
}

pub(super) fn synchronization_point_achieved(
    node: &Arc<RtiNode>,
    ctx: &mut SessionContext,
    callbacks: &mut Vec<OutboundCallback>,
    label: String,
    successfully: bool,
) -> Resp {
    use hla_fedpro_proto::fedpro::SynchronizationPointAchievedResponse;

    let m = match ctx.membership.as_ref() {
        Some(m) => m.clone(),
        None => return exception_variant(HlaException::FederateNotExecutionMember, ""),
    };

    let synced_now = {
        let mut sync_points = m.federation.sync_points.write();
        let sp = match sync_points.get_mut(&label) {
            Some(s) => s,
            None => {
                return exception_variant(
                    HlaException::SynchronizationPointLabelNotAnnounced,
                    &label,
                );
            }
        };
        if !sp.participants.contains(&m.federate_handle) {
            return exception_variant(
                HlaException::FederateNotInSynchronizationGroup,
                &format!(
                    "federate {} not in sync set for {label}",
                    m.federate_handle.raw()
                ),
            );
        }
        sp.achieved.insert(m.federate_handle);
        if !successfully {
            sp.failed_to_sync.insert(m.federate_handle);
        }
        if sp.achieved.len() == sp.participants.len() {
            // All achieved — pull the sync point out and emit FederationSynchronized.
            Some(sync_points.remove(&label).unwrap())
        } else {
            None
        }
    };

    if let Some(sp) = synced_now {
        let conns = live_connections(node, &m.federation, &sp.participants);
        fan_out(
            callbacks,
            &conns,
            federation_synchronized(&label, &sp.failed_to_sync),
        );
    }

    Resp::SynchronizationPointAchievedResponse(SynchronizationPointAchievedResponse {})
}
